// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIR4ht1rH3WBOKEFnNeR6LD-mAdbhOgGM',
    appId: '1:629030722509:web:e5a24cdbba0db4dd920284',
    messagingSenderId: '629030722509',
    projectId: 'ccaves-app',
    authDomain: 'ccaves-app.firebaseapp.com',
    storageBucket: 'ccaves-app.appspot.com',
    measurementId: 'G-4GEQVJ3W1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7D5xoaTyin7gFuQyGqnSLVrwRhbp5FXI',
    appId: '1:629030722509:android:00c45f9190c70c38920284',
    messagingSenderId: '629030722509',
    projectId: 'ccaves-app',
    storageBucket: 'ccaves-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZYQKnzSFInbZdAsrXp6NS6yokfhxRUsU',
    appId: '1:629030722509:ios:e26e5bce8c0b6d31920284',
    messagingSenderId: '629030722509',
    projectId: 'ccaves-app',
    storageBucket: 'ccaves-app.appspot.com',
    iosClientId: '629030722509-rg17asjeal2ke8cegju77vip966a3gjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccavesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZYQKnzSFInbZdAsrXp6NS6yokfhxRUsU',
    appId: '1:629030722509:ios:e26e5bce8c0b6d31920284',
    messagingSenderId: '629030722509',
    projectId: 'ccaves-app',
    storageBucket: 'ccaves-app.appspot.com',
    iosClientId: '629030722509-rg17asjeal2ke8cegju77vip966a3gjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccavesApp',
  );
}
